model_config:
  Vanilla:
    num_layers: 3
    in_channels: 3
    out_channels: 16
    k: 3
    stride: 1
  
  Octave:
    num_layers: 10
    out_channels: [32, 32, 64, 64, 128, 128, 128, 128, 128, 128]
    octave_alpha: [0.5, 0.5, 0.375, 0.375, 0.25, 0.25, 0.125, 0.125, 0.125, 0.00]
    stride: [1, 2, 1, 2, 1, 2, 1, 1, 1, 1]
    max_pool: [0, 0, 0, 0, 0, 0, 0, 2, 0, 2]

  Separable_DepthWise_Block:
    num_layers: 3
    out_channels: 256
    stride: "2x1"
    activation: "relu"
    dropout: 0.4